baseurl= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "hugo-theme-yinyang"
title= "Ritesh Sinha's blog"
Paginate = 10
SectionPagesMenu = "main"
canonifyurls = false
disableKinds = ["taxonomy", "taxonomyTerm"]
[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
[params]
	mainSections = ["posts"]
	headTitle = "Ritesh Sinha"
[[params.socials]]
	name = "Twitter"
	link = "https://twitter.com/rsinha"
[[params.socials]]
	name = "Github"
	link = "https://github.com/ritesh"
[[params.socials]]
	name = "About Me"
	link = "/about/"
[taxonomies]
	tag = "tags"
	series = "series"
