baseurl= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "PaperMod"
title= "Ritesh's Ramblings"
Paginate = 10
SectionPagesMenu = "main"
canonifyurls = false
[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
[[menu.main]]
	identifier = "example"
	name = "About"
	url = "/about/"
	weight = 10	
[params]
	mainSections = ["posts"]
	headTitle = "Ritesh Sinha"
	env = "production"
	defaultTheme = "dark"
	ShowShareButtons = false
	author = "rsinha"
[[params.socials]]
	name = "Twitter"
	link = "https://twitter.com/rsinha"
[[params.socials]]
	name = "Github"
	link = "https://github.com/ritesh"
[[params.socials]]
	name = "About Me"
	link = "/about/"
