baseURL= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "hugo-PaperMod"
title= "Ritesh's Ramblings"
canonifyurls = false
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
enableRobotsTXT = true
googleAnalytics = "UA-65020746-1"

[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = false
		tabWidth = 4

[languages]
	[languages.en]
		title = "Ritesh's Ramblings"
		weight = 1
		contentDir = "content"

[params]
	mainSections = ["posts"]
	defaultTheme = "dark"
	description = "A weird collection of posts"
	author = "rsinha"
	ShowReadingTime = true
	ShowCodeCopyButtons = true

[[params.socialIcons]]
	name = "twitter"
	url = "https://twitter.com/rsinha"
[[params.socialIcons]]
	name = "github"
	url = "https://github.com/ritesh"
