baseURL= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "ananke"
title= "Ritesh's Ramblings"
canonifyurls = false
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
enableRobotsTXT = true

[languages]
	[languages.en]
		title = "Ritesh's Ramblings"
		weight = 1
		contentDir = "content"
[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
[params]
	mainSections = ["posts"]
	defaultTheme = "dark"
	description = "A weird collection of posts"
	background_color_class = "bg-black"
	author = "rsinha"
[[params.ananke_socials]]
	name = "Twitter"
	link = "https://twitter.com/rsinha"
[[params.ananke_socials]]
	name = "Github"
	link = "https://github.com/ritesh"
