baseurl= "https://blog.rsinha.org/"
languageCode= "en-gb"
theme = "hugo-PaperMod"
title= "Ritesh's Ramblings"
Paginate = 10
SectionPagesMenu = "main"
canonifyurls = false
[author]
	Handle = "rsinha"
	FirstName = "Ritesh"
	LastName = "Sinha"
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 10	
[params]
	mainSections = ["posts"]
	headTitle = "Ritesh Sinha"
	env = "production"
	defaultTheme = "dark"
	ShowShareButtons = false
	author = "rsinha"
[params.homeInfoParams]
Title = "Hi there!"
Content = """\
Hello! I'm Ritesh. 
If you'd like to get in touch or want to say hi, 
find me on twitter [@rsinha](https://twitter.com/rsinha).
 I probably spend more time tweaking the CSS on this blog as opposed to writing any useful content. 
 Going to try and write more soon! \
"""
[[params.socialIcons]]
foo = "bar"
foo2 = "bar"

[[params.socials]]
	name = "Twitter"
	link = "https://twitter.com/rsinha"
[[params.socials]]
	name = "Github"
	link = "https://github.com/ritesh"
[[params.socials]]
	name = "About Me"
	link = "/about/"
