---
label: Post
hide_body: false
is_partial: false
fields:
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
- name: summary
  label: Summary
  type: textarea
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: url
  label: Url
  type: text
  hidden: false
  default: ''
